baseURL = "https://thunderous-bublanina-68f8ff.netlify.app"
languageCode = "fr"
theme = "congo"
paginate = 10

[pagination]
  pagerSize = 10

[params]
  colorScheme = "congo"
  accentColor = "neutral"
  list_layout = "blog"

  [params.author]
    name = "Dylan"

  [params.homepage]
    showRecent = true
    cardView = true
    limit = 10

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Galerie"
    url = "/galerie/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 70
