[build]
  command = "hugo --theme congo --gc --minify --environment production"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.140.0"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
