backend:
  name: git-gateway
  branch: main

media_folder: "static/img/faune" # Où seront stockées les photos
public_folder: "/img/faune"

collections:
  - name: "posts"
    label: "Articles Photo"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Catégorie", name: "categories", widget: "list"}
      - {label: "Image Principale", name: "image", widget: "image"}
      - {label: "Corps du texte", name: "body", widget: "markdown"}